{% set version = "3.5.22" %}

package:
  name: mcstas-suite
  version: {{ version }}

# sha256 value manually found by
# curl -sL url | openssl sha256
source:
  url: https://github.com/McStasMcXtrace/McCode/archive/v{{ version }}.tar.gz
  sha256: a7e5ac1a7b5faec6effe61c443402a8856b7655b02b178297f6f836836deb656
  folder: src

build:
  number: 0

outputs:

  - name: mcstas-core
    script: install-files-core.sh  # [unix]
    script: install-files-core.bat  # [win]
    requirements:
      build:
        - cmake
        - make  # [unix]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - flex  # [unix]
        - bison  # [unix]
        - winflexbison  # [win]
      host:
        - dirent  # [win]
      run:
        - python
        - c-compiler
        - {{ stdlib("c") }}
        - bash  # [unix]
        # for mcrun
        - pyaml
        - numpy
        - mslex  # [win]
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py core
      source_files:
        - src/mcstas-comps/examples/BNL/BNL_H8/BNL_H8.instr
        - src/mcstas-comps/examples/Union_demos/Manual_example/Manual_example.instr

  - name: mcstas-data
    build:
      noarch: generic
    script: install-files-data.sh  # [unix]
    script: install-files-data.bat  # [win]
    test:
      files:
        - test_pkg.py
      requires:
        - python
      commands:
        - python test_pkg.py data

  - name: mcstas-mcgui
    requirements:
      run:
        - mcstas-core
        - pyqt
        - qscintilla2
    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py mcgui

  - name: mcstas-vis
    requirements:
      run:
        - mcstas-core
        #  Note: conda-forge linter wants matplotlib-base and not matplotlib. It
        #  actually makes no difference (as per October 2023) since we anyway
        #  install tornado+pyqt.
        - matplotlib-base
        - numpy
        - tornado >=5
        - scipy
        - pillow
        - pyqtgraph
        - pyqt >=5.10
        - qtpy
        - nodejs
        # for traces from mcdisplay
        - ply
        # for sync of 3D / js files
        - rsync  # [unix]
        # for visualisation of test output
        - jinja2
        # McStasscript and jupyter support
        - mcstasscript
        - jupytext
        - jupyterlab
        - m2-which  # [win]
        - m2-sed  # [win]
        - m2-gzip  # [win]

    test:
      files:
        - test_pkg.py
      commands:
        - python test_pkg.py vis

  - name: mcstas
    test:
      files:
        - test_pkg.py
      requires:
      commands:
        - python test_pkg.py mcstas
    requirements:
      run:
        - {{ pin_subpackage('mcstas-core', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcstas-data', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcstas-mcgui', max_pin="x.x.x") }}
        - {{ pin_subpackage('mcstas-vis', max_pin="x.x.x") }}
        - msmpi  # [win]
        - openmpi=4  # [unix]
        - ucx  # [linux]
        - gsl
        - libnexus
        - nexpy
        - cif2hkl
        - mcpl  # [unix]
        - ncrystal >= 4.0

about:
  home: https://mcstas.org/
  summary: McStas is a general tool for simulating neutron scattering instruments and experiments.
  description: |
    McStas is a general tool for simulating neutron scattering instruments and
    experiments.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: src/COPYING
  doc_url: https://mcstas.org/
  dev_url: https://github.com/McStasMcXtrace/McCode

extra:
  recipe-maintainers:
    - willend
    - tkittel
